server:
  port: 8080
  tomcat:
    max-http-post-size: 0
# 监听端口和保存路径
image:
  cutY: 30
  cutX: 0
  io:
    originImagePath: c:/pictures/origin/
    combinedImagePath: c:/pictures/combined/
    printedImagePath: c:/pictures/printed/
    backgroundImagePath: c:/pictures/background/
# 日志设定
logging:
  level:
    com.sagacn: INFO
  config: classpath:logback-prod.xml
spring:
  http:
    multipart:
      max-file-size: 10mb