server:
  port: 8080

# 监听端口和保存路径
image:
  io:
    originImagePath: c:/origin/
    combinedImagePath: c:/combined/
    printedImagePath: c:/printed/
    backgroundImagePath: c:/background/
# 日志设定
logging:
  level:
    com.sagacn: INFO
  config: classpath:logback-prod.xml
